### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by allthesignals** [allthesignals/avocado#10]
- [ ] Beef up the tile serving feature
   - [ ] Performance tests
   - [ ] Caching layer (@allthesignals)
   - [ ] Infer table relationships to automate & populate an API structure (REST/or more structure) (@stuartlynn)
     - [ ] ORM structure? GraphQL?
     - [ ] **Meld together a "REST"yness with the MVT spec...**
 - [ ] Rebuild a real-world use-case of this API (ZoLa, ZAP Search, etc.) (@allthesignals)
